export const UserPlaceholder = {
    firstName: '',
    lastName: '',
    profilePicture: { location: '', key: '' },
    socialPicture: '',
    username: '',
    email: '',
    userType: 'Student',
    posts: [],
    classrooms: [],
    assignments: [],
    coins: 0,
    xp: 0,
    level: 0,
    ownedAvatars: [],
    avatar: '',
    items: [],
    confirmationCode: '',
    loginType: '',
    admin: false,
    _id: ''
};
